### ISSUE TITLE
IoT Workbench release 0.1.0 candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [microsoft/vscode-iot-workbench#141]
Feature:
- [x] #137 Add a device selection step
- [x] #134 Change ShakeShake example to IoT Hub triggered
- [x] #122 Create icon for the extension of Iot workbench
- [x] #140 Change the commands structure

Bug:
- [x] #133 .iotworkbenchproject file without any content 
- [x] #131 No readme in Getstarted project
- [x] #126 "Esc" key doesn't work correctly [Toolkit issue]
- [x] #125 Better UI to show error message
- [x] #124 An error displays if set sketch file name to absolute path
- [x] #117 "Device Upload" failed as the sketch file contains white space
- [x] #114 If no workspace open, the error message should be keep consistent
- [x] #106 If az logout, user is blocked at "select subscription" step or "select resource group" step
- [x] #80 Need more comments in the MQTT code snippet
- [x] #26 Handle promise reject better 
- [x] #142 Not create duplicate sample under same folder
