### ISSUE TITLE
Public Preview 0.1.1 Candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-iot-workbench#186]
- [x] #180 Auto downloading the package of AZ3166
- [x] #159 The output folder is not specified
- [x] #152 If workspace is not empty and try to create a new project, the message should be keep consistent
- [x] #126 "Esc" key doesn't work correctly
- [x] #112 An error displays when create new storage account
- [x] #187 New welcome window experience
- [x] #188 New project catalog
- [x] #189 User data collection and GDPR
