### ISSUE TITLE
Public Preview 0.1.6 Candidates

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#266]
- [x] #264 Support example gallery with different boards 
- [x] #265  Enable the test framework for IoT Workbench 
- [x] #267  Update the document of current mini solutions to use IoT Workbench 
- [x] #304   Support Raspberry Pi in IoT workbench
- [x] #292 Still popup "please hold on button A..." notification after set the connection string sucessfully
