### ISSUE TITLE
IoT Workbench Public preview 0.1.9

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#329]
- [x] #305 Support ESP32 in IoT workbench 
- [x] #313 For IoT-Devkit, support setting UDS in configure device setting 
- [x] #289 Replace 'tag parser' for intellisense setting 
- [x] #325 [Raspberry Pi][Doc] Improve the doc of raspi-get-started and raspi-simple-led 
- [x] #330 Support new template for Azure Steam Analytics 
- [x] #331 Add get started document for ESP32 device
