### ISSUE TITLE
IoT Workbench public preview 0.1.10

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#400]
- [x] #399 Show a welcome page when the user activates IoT workbench for the first time 
- [x] #390 Add more examples for ESP32 devices in IoT workbench 
- [x] #389 Create the example main page for ESP32 devices 
- [x] #381 Improve the experience of OTA for IoT DevKit in IoT workbench
