### ISSUE TITLE
IoT Workbench public preview 0.1.11

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#429]
- [] #420  [Generate CRC]improve the message to tell user run device complie 
- [] #419 [doc] improve the steps of OTA tutorial 
- [] #391 Refactor IoT Devkit examples 
- [] #174 Update Azure function part to use beta version of C#Library
