### ISSUE TITLE
IoT Workbench public preview 0.1.13

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#448]
- [x] #420  [Generate CRC]improve the message to tell user run device complie 
- [x] #419 [doc] improve the steps of OTA tutorial 
- [x] #391 Refactor IoT Devkit examples 
- [x] #434 Provide a configure to disable auto loading example page

**Comment by lirenhe** [comment]
Released
