### ISSUE TITLE
IoT Workbench release 0.1.14

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#488]
- [x] #474 [User experience]: Remove the file name input window for creating new project 

- [x] #473 [User experience]: improve the experience when creating a new project 

- [x] #476 [User experience]: Improve the experience of setting device connection 

- [x] #477 [User experience]: Better handle the case when the project is not opened as a workspace 

- [x] #480 Upgrade to VS Code's webview API 

- [x] #437 Setting the Device Connection String doesn't work through vscode on MacOS
