### ISSUE TITLE
IoT Workbench release 0.2.0

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#514]
- [x] #511 Update the Welcome page

- [x] #512 Flatten all the F1 commands for IoT Workbench

- [x] #513 Modify all document with the new command name

- [x] #500 [Doc][IoT button] update the step of "Create IoT Project"

- [x] #489 Support Azure China environment

- [x] #479 Use c# library for DevKit examples
