### ISSUE TITLE
IoT Workbench release 0.2.2

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#549]
- [x] Update the example main page.

- [x] Add more examples into IoT DevKit example gallery

- [x] #550  Remove the dependency of Azure Function extension

- [x] #464 Add IoT Workbench sample for IoT Central

- [x] #367 Verify and provide guide on Mooncake for IoT workbench
