### ISSUE TITLE
Release 0.2.3

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#565]
- [ ] #555 Use Buffer.from instead of Buffer for Node 11 

- [ ] #554 Upgrade binary dependency for electron 3.0 

- [ ] #409 Remove the dependency of Arduino extension
